### ISSUE TITLE
Conditional Formatting for Goal and Milestone Cards

### ISSUE THREAD

**Issue by jbped** [EastonShaum/Goal-Getter#19]
## Description
Create JS file that changes goal and milestone card styles dependent on their status.

#### Active
![Active Goal](https://user-images.githubusercontent.com/76881086/127762830-f1bfca07-0c8b-4e9d-ae25-53304d334659.png)
Toggle between red and green date colors (Class = text-danger and text-success respectively).

Update progress bar on count of milestones complete vs associated to goal. May need to add two addition sequelize literals, one to count completed milestones and one for total milestones, both of which are associated to the specific goal.

Get the one with the closest due date.

#### Completed
![image](https://user-images.githubusercontent.com/76881086/127762941-dad61461-bb2f-457d-ba54-7ae036ccbbfa.png)

Remove milestone information and progress bar. Add trophy icon. Change due date to "Completed"

### Milestone Cards: 
Change the icon (red checklist - to do, silver hourglass - in progress, gold medal - completed) dependent on selected drop down. Push update to db as well.

Toggle between red and green date colors (Class = text-danger and text-success respectively).

![image](https://user-images.githubusercontent.com/76881086/127763003-71946611-8e17-4cff-9fe4-895616307660.png)

**Comment by jvesterfelt** [comment]
Goal card done.

**Comment by jvesterfelt** [comment]
Milestone card functionality complete.
