### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by EastonShaum** [EastonShaum/Goal-Getter#2]
Create Tables:Team: 
	ID
	Name
	Fk leader(user)
	Fk goals
	Fk members(user)

User: 
	ID
	First Name
	Last Name
	Email Address
	Fk goals
	Fk Team
	
Goals:
	Id
	hasMilestones - Boolean
	Title
	Description
	Created_at
	Due_date
	isPublic- Boolean
	Accomplishment
Fk_tags
fk  user_id
Fk team_id

Milestones:
	Id
	Title
	Description
	Created_at
            Due-date
            isPublic- Boolean
	Fk_goals
            Fk user_id

Goal_comment: 
         Id
           Comment
         Timestamp
         Milestone_id
         goal_id

Tags:
	Id
	Name
	Desc

(Optional) Friends:
            Id
            Fk user

**Comment by jvesterfelt** [comment]
Complete
